function [outstr] = make_hstruct_in(size,poly_order,k_sampling,k_grid,...
                                    max_level,level,num_CV,...
                                    outdir,tempdir)
  outstr = [...
    'STRUCT INPUTFILE\n',...
    'JOB_NAME = ml_mos2_mlmc\n\n',... % Name of job, will prefix all files
    '===STRUCTURE INFORMATION===\n\n',... 
    'MAXSIZE = ',int2str(size+1),'\n',...
    'MINSIZE = 0 \n',...
    'BOUNDARY_CONDITION = 1\n\n',... % periodic BCs
    'SUPERCELL_GRID = ',int2str(size),' ',int2str(size),'\n',...
    'K_SAMPLING = ',int2str(k_sampling),'\n',...
    'K_GRID = ',int2str(k_grid),' ',int2str(k_grid),'\n',...
    'NUM_SHEETS = 1\n\n',... % Rest is geometery information for the TMDC
    'START_SHEET 1\n\n',...
    'MATERIAL = MoS2\n\n',...
    'HEIGHT = 0\n',...
    'ANGLE = 0\n\n',...
    'END_SHEET 1\n\n',...
    '===SOLVER INFORMATION==\n\n',... % Run settings
    'SOLVER_TYPE = MLMC_VAC\n\n',...  % We are doing a MLMC sample
    'OBSERVABLE_TYPE = COND\n',...    % Want to calculate Conductivity
    'DIAGONALIZE = 1\n',... % do explicit diagonalization with Eigen lib
    'D_WEIGHTS = 0\n',...   % no eigen-weights
    'D_VECS = 0\n',...      % no eigen-vectors
    'D_COND = 1\n\n',...    % just does M_XX, set = 2 for M_YY and M_XY
    'NUM_TARGET_SHEETS = 1\n',...
    'TARGET_SHEETS = 1\n',...
    'NUM_SHIFT_SHEETS = 1\n',...
    'SHIFT_SHEETS = 1\n\n',...
    'MLMC = 1\n',...
    'MLMC_MAX_LEVEL = ',int2str(max_level),'\n',... % Max level of calc
    'MLMC_LEVEL = ',int2str(level),'\n',...         % Current level
    'MLMC_NUM_CLUSTERS = ',int2str(num_CV),'\n',... % Total number of CVs
    'MLMC_CLUSTER_SIZE = 4\n',...   % Number of pieces we cut the CV into
    'MLMC_OUT_ROOT = ',outdir,'\n',...
    'MLMC_TEMP_ROOT = ',tempdir,'\n',...
    'VACANCY_FILE = vacancies.dat\n\n',...  % Where to read Vac info from
    'INTRA_SEARCHSIZE = 3\n',...
    'INTER_SEARCHSIZE = 3\n',...
    'ENERGY_RESCALE = 7\n',...
    'ENERGY_SHIFT = 0\n',...
    'POLY_ORDER = ',int2str(poly_order),'\n\n',...
    ];

end